run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck    # Check for unchecked errors
    - gosimple    # Detect simplifications in Go code
    - govet       # Report suspicious constructs
    - staticcheck # Go static analysis
    - unused      # Check for unused code
    - revive      # Enhanced linting tool

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 3

output:
  formats: colored-line-number
