name: gin-boilerplate
networks:
  own_network:
    driver: bridge
services:
  mongo:
    build:
      dockerfile: .docker/mongo/Dockerfile
    container_name: gin-boilerplate-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - '${MONGO_PORT}:27017'
    command: --replSet rs0 --keyFile /etc/mongo-keyfile --bind_ip_all --port 27017
    healthcheck:
      test: >
        sh -c "sleep 10 && echo '
          try { rs.status() }
          catch (err) {
            rs.initiate({
              _id: \"rs0\",
              members:[
                { _id: 0, host: \"127.0.0.1:27017\" }
              ]
            })
          }' | mongosh --port 27017 -u ${MONGO_USERNAME} -p ${MONGO_PASSWORD} --authenticationDatabase admin"
      interval: 0s
      timeout: 15s
      start_period: 15s
      retries: 10
    networks:
      - own_network
    volumes:
      - gin_boilerplate_db:/data/db
volumes:
  gin_boilerplate_db:
