// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wires

import (
	"github.com/hainguyen27798/gin-boilerplate/internal/module/users"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Injectors from user_wire.go:

// InitializeUserModule sets up the UserController with its dependencies.
func InitializeUserModule(db *mongo.Database) *users.UserController {
	userRepository := users.NewUserRepository(db)
	userService := users.NewUserService(userRepository)
	userController := users.NewUserController(userService)
	return userController
}
